### ISSUE TITLE
Pydio 9 License

### ISSUE THREAD

**Issue by bures** [pydio/pydio9-beta-docs#1]
I'm very excited about the new Pydio. We are introducing Pydio 8 in our NGO. As part of our larger roadmap for adoption, I would like to ask whether there will be again source code available for Pydio 9 (including the Go part)? I checked pydio-core, this however does not seem to have the source code for the Go microservices.

It's important for us that we can extend Pydio for the requirements we have in our NGO. I've already created an alternative plugin for matadata with the ability to have hierarchical categories and search that takes into account the hierarchy of terms. I'll be very happy to open source the plugin for Pydio. The only problem is that it's not a drop in replacement for meta.user, as it lacks some of its features. 

Thanks.

**Comment by cdujeu** [comment]
Hey Tomas
The Go code will be available indeed, probably in a couple of weeks. We kind of kept it in stealth mode for this tech preview :-). And it will be OS-licensed as well.
Charles

**Comment by bures** [comment]
Excellent! Thank you very much for all this wonderful work! I really like so much the modular architecture that Pydio has. It makes it so easy to extend it. Thanks.
